name: Build

on: [push]

jobs:
  windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: npx tsc --resolveJsonModule

      - name: Compile executable
        run: npx electron-builder

  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: npx tsc --resolveJsonModule

      - name: Compile executable
        run: npx electron-builder

  macos:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: npx tsc --resolveJsonModule

      - name: Compile executable
        run: npx electron-builder
