name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build-command: bun run build linux
            artifacts: |
              dist/*.deb
              dist/*.AppImage
              dist/*.rpm
              dist/*.snap
          - os: windows-latest
            build-command: bun run build windows
            artifacts: dist/*.exe
          - os: macos-latest
            build-command: bun run build macos
            artifacts: dist/*.dmg

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: ${{ matrix.build-command }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.artifacts }}
          name: ${{ runner.os }}-artifacts
          if-no-files-found: error
